const MODES=[['sd','式舆防卫'],['da','危局强袭']];
const ROLES=[['all','全部'],['crit_dps','直伤主C'],['anomaly_dps','异常主C'],['support','辅助'],['unknown','未分类']];
const VIEWS=[['trend','趋势'],['latest','排行'],['heatmap','热力']];
const ELEMENTS=['物理','火','冰','电','以太','风','玄墨'];
const STYLES=['强攻','异常','击破','支援','防护','命破'];
const TIER_RANK={'T0':0,'T0.5':.5,'T1':1,'T1.5':1.5,'T2':2,'T3':3,'T4':4,'T5':5,'未分档':9};
const BUILD_LEVELS=[0,20,40,50,55,60], BUILD_SKILLS=[['unset','未录入',0],['low','低',.35],['mid','中',.6],['high','高',.84],['max','满',1]], BUILD_DISCS=[['unset','未录入',0],['none','未刷',.12],['ok','可用',.58],['good','成型',.84],['great','毕业',1]];
const BOX_KEY='zzz_endgame_box_v1', REC_KEY='zzz_endgame_rec_v1';
let DATA=null,state={page:'analysis',mode:'sd',role:'all',view:'trend',limit:'16',search:''},box={owned:new Set(),builds:{},buildSlug:'',element:'all',style:'all',status:'all',search:''},rec={mode:'sd',scope:'',elements:{},gap:'1',riskMode:'warn',limit:'8',search:''};
const $=id=>document.getElementById(id), num=v=>{const n=Number(v);return Number.isFinite(n)?n:null}, esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])), pct=v=>num(v)==null?'-':`${num(v).toFixed(2)}%`;
fetch('./data.json').then(r=>r.json()).then(d=>{DATA=d;loadBox();loadRec();init();render();}).catch(e=>document.body.innerHTML=`<main class="app"><h1>数据加载失败</h1><p>${esc(e.message)}</p></main>`);
function init(){ $('metaLine').textContent=`Prydwen更新：${DATA.meta.tierUpdatedAt||'未知'} · 本地生成：${DATA.meta.generatedAt||'未知'}`; buttons('tabs',[['analysis','趋势分析'],['box','我的Box'],['recommender','组队推荐']],state.page,v=>{state.page=v;render();}); buttons('modeControl',MODES,state.mode,v=>{state.mode=v;render();}); buttons('roleControl',ROLES,state.role,v=>{state.role=v;render();}); buttons('viewControl',VIEWS,state.view,v=>{state.view=v;render();}); $('limitSelect').onchange=e=>{state.limit=e.target.value;renderAnalysis();}; $('searchInput').oninput=e=>{state.search=e.target.value.trim().toLowerCase();renderAnalysis();}; initBox(); initRec();}
function buttons(id,items,current,onClick){const el=$(id); el.innerHTML=''; items.forEach(([v,l])=>{const b=document.createElement('button');b.type='button';b.textContent=l;b.dataset.value=v;b.className=v===current?'active':'';b.onclick=()=>{[...el.children].forEach(x=>x.classList.remove('active'));b.classList.add('active');onClick(v);};el.appendChild(b);});}
function render(){ $('analysisView').classList.toggle('hidden',state.page!=='analysis');$('boxView').classList.toggle('hidden',state.page!=='box');$('recommenderView').classList.toggle('hidden',state.page!=='recommender');[...$('tabs').children].forEach(b=>b.classList.toggle('active',b.dataset.value===state.page)); if(state.page==='box')renderBox();else if(state.page==='recommender')renderRec();else renderAnalysis();}
function charInfo(slug){return (DATA.rosterRows||[]).find(r=>r.character_slug===slug)||{character_slug:slug,character_name_cn:'',character_name_en:slug,element_cn:'',style_cn:'',role_group:'unknown',role_group_cn:'未分类',tier:'未分档',icon_url:''};}
function charName(slug){const r=charInfo(slug);return r.character_name_cn||r.character_name_en||slug}
function bangbooName(slug, fallback=''){const r=(DATA.nameRows||[]).find(x=>x.character_slug===slug);return fallback||r?.character_name_cn||r?.character_name_en||slug||'-'}
function filteredUsage(){const q=state.search; return (DATA.usageRows||[]).filter(r=>r.mode===state.mode&&r.sub_mode==='all'&&(state.role==='all'||(charInfo(r.character_slug).role_group===state.role))&&(!q||[r.character_name_cn,r.character_name_en,r.character_slug,charInfo(r.character_slug).element_cn,charInfo(r.character_slug).style_cn].some(x=>String(x||'').toLowerCase().includes(q))));}
function seriesRows(){const map=new Map();filteredUsage().forEach(r=>{if(!map.has(r.character_slug))map.set(r.character_slug,[]);map.get(r.character_slug).push(r);});return [...map.entries()].map(([slug,rows])=>{rows.sort((a,b)=>String(a.collect_date).localeCompare(String(b.collect_date)));return{slug,rows,latest:rows[rows.length-1]};}).sort((a,b)=>(num(b.latest.app_rate)||0)-(num(a.latest.app_rate)||0)).slice(0,Number(state.limit)||16);}
function renderAnalysis(){const series=seriesRows();$('chartTitle').textContent=`${MODES.find(x=>x[0]===state.mode)?.[1]} · ${ROLES.find(x=>x[0]===state.role)?.[1]} · ${VIEWS.find(x=>x[0]===state.view)?.[1]}`;$('chartSubtitle').textContent=`展示 ${series.length} 个代理人，指标为出场率 / 平均分`; $('badges').innerHTML=[`角色 ${DATA.rosterRows.length}`,`样本点 ${filteredUsage().length}`].map(x=>`<span>${x}</span>`).join(''); state.view==='latest'?drawBars(series):state.view==='heatmap'?drawHeatmap(series):drawLines(series);renderCharacterList(series);renderChangelog(series);}
function chartBox(){const svg=$('chart');svg.innerHTML='';const rect=svg.getBoundingClientRect();const w=Math.max(760,rect.width||1000),h=620;svg.setAttribute('viewBox',`0 0 ${w} ${h}`);return{svg,w,h};}
function add(svg,tag,attrs){const n=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));svg.appendChild(n);return n;}
function drawLines(series){const {svg,w,h}=chartBox();if(!series.length){add(svg,'text',{x:40,y:60,class:'axis'}).textContent='暂无数据';return;}const defs=add(svg,'defs',{});const dates=[...new Set(series.flatMap(s=>s.rows.map(r=>r.collect_date)))].sort();const max=Math.max(1,...series.flatMap(s=>s.rows.map(r=>num(r.app_rate)||0)));const m={l:70,r:44,t:42,b:60},cw=w-m.l-m.r,ch=h-m.t-m.b;const x=d=>m.l+(dates.indexOf(d)/Math.max(1,dates.length-1))*cw,y=v=>m.t+ch-(v/max)*ch;for(let i=0;i<=5;i++){const yy=m.t+ch*i/5;add(svg,'line',{x1:m.l,y1:yy,x2:m.l+cw,y2:yy,class:'grid'});add(svg,'text',{x:m.l-8,y:yy+4,'text-anchor':'end',class:'axis'}).textContent=(max*(1-i/5)).toFixed(0);}dates.forEach((d,i)=>{if(dates.length>12&&i%2)return;add(svg,'text',{x:x(d),y:m.t+ch+24,'text-anchor':'middle',class:'axis'}).textContent=d.slice(5);});series.forEach((s,i)=>{const color=['#2563eb','#dc2626','#16a34a','#9333ea','#ea580c','#0891b2'][i%6];const pts=s.rows.map(r=>[x(r.collect_date),y(num(r.app_rate)||0),r]).filter(p=>Number.isFinite(p[1]));add(svg,'path',{d:pts.map((p,j)=>`${j?'L':'M'}${p[0]} ${p[1]}`).join(' '),stroke:color,class:'line'});pts.forEach(([xx,yy,row],pi)=>drawAvatarPoint(svg,defs,xx,yy,row,s.slug,color,i,pi));});}
function drawAvatarPoint(svg,defs,x,y,row,slug,color,seriesIndex,pointIndex){const info=charInfo(slug),r=11,href=info.icon_url||row.icon_url;if(href){const clipId=`clip-${seriesIndex}-${pointIndex}-${Math.round(x)}-${Math.round(y)}`;const clip=add(defs,'clipPath',{id:clipId});add(clip,'circle',{cx:x,cy:y,r});const img=add(svg,'image',{href,x:x-r,y:y-r,width:r*2,height:r*2,'clip-path':`url(#${clipId})`,class:'avatar'});add(svg,'circle',{cx:x,cy:y,r,fill:'none',stroke:color,class:'avatar-ring'});img.addEventListener('mouseenter',e=>showChartTip(e,row));img.addEventListener('mousemove',moveTip);img.addEventListener('mouseleave',()=>{$('tooltip').hidden=true;});}else{const c=add(svg,'circle',{cx:x,cy:y,r:4.8,fill:color});c.addEventListener('mouseenter',e=>showChartTip(e,row));c.addEventListener('mousemove',moveTip);c.addEventListener('mouseleave',()=>{$('tooltip').hidden=true;});}}
function drawBars(series){const {svg,w,h}=chartBox();const m={l:170,r:80,t:36,b:36},rowH=Math.max(32,Math.min(44,(h-m.t-m.b)/Math.max(series.length,1)));const max=Math.max(1,...series.map(s=>num(s.latest.app_rate)||0));series.forEach((s,i)=>{const y=m.t+i*rowH+rowH/2,val=num(s.latest.app_rate)||0,x=m.l+(val/max)*(w-m.l-m.r),info=charInfo(s.slug);add(svg,'text',{x:18,y:y+4,class:'axis'}).textContent=`${i+1}. ${charName(s.slug)}`;add(svg,'line',{x1:m.l,y1:y,x2:x,y2:y,stroke:'#174c5a',class:'bar'});add(svg,'text',{x:x+14,y:y+4,class:'axis'}).textContent=pct(val);});}
function drawHeatmap(series){const {svg,w,h}=chartBox();if(!series.length){add(svg,'text',{x:40,y:60,class:'axis'}).textContent='暂无数据';return;}const dates=[...new Set(series.flatMap(s=>s.rows.map(r=>r.collect_date)))].sort();const m={l:180,r:30,t:54,b:42},gap=3,rowH=Math.max(24,Math.min(34,(h-m.t-m.b)/Math.max(series.length,1))),cw=Math.max(12,(w-m.l-m.r-(dates.length-1)*gap)/Math.max(dates.length,1));const max=Math.max(1,...series.flatMap(s=>s.rows.map(r=>num(r.app_rate)||0)));dates.forEach((d,j)=>{if(dates.length>14&&j%2)return;add(svg,'text',{x:m.l+j*(cw+gap)+cw/2,y:m.t-18,'text-anchor':'middle',class:'axis'}).textContent=d.slice(5);});series.forEach((s,i)=>{const y=m.t+i*rowH;add(svg,'text',{x:18,y:y+rowH/2+4,class:'heat-name'}).textContent=`${i+1}. ${charName(s.slug)}`;const byDate=new Map(s.rows.map(r=>[r.collect_date,r]));dates.forEach((d,j)=>{const r=byDate.get(d),val=num(r?.app_rate)||0,intensity=Math.max(.06,Math.min(1,val/max));const rect=add(svg,'rect',{x:m.l+j*(cw+gap),y:y+4,width:cw,height:rowH-8,fill:`rgba(23,76,90,${intensity})`,class:'heat-cell'});if(r){rect.addEventListener('mouseenter',e=>showChartTip(e,r));rect.addEventListener('mousemove',moveTip);rect.addEventListener('mouseleave',()=>{$('tooltip').hidden=true;});}});});}
function showChartTip(evt,row){const tt=$('tooltip');tt.innerHTML=`<div class="tooltip-grid"><b>角色</b><span>${esc(charName(row.character_slug))}</span><b>日期</b><span>${esc(row.collect_date)}</span><b>出场率</b><span>${pct(row.app_rate)}</span><b>平均分</b><span>${esc(row.avg_score||'-')}</span><b>期数</b><span>${esc(row.phase_name||row.phase_ver||'-')}</span></div>`;tt.hidden=false;moveTip(evt);}
function moveTip(evt){const tt=$('tooltip');let x=evt.clientX+16,y=evt.clientY+16;const r=tt.getBoundingClientRect();if(x+r.width+12>innerWidth)x=evt.clientX-r.width-16;if(y+r.height+12>innerHeight)y=evt.clientY-r.height-16;tt.style.left=`${Math.max(12,x)}px`;tt.style.top=`${Math.max(12,y)}px`;}
function renderCharacterList(series){const boxEl=$('characterList');if(!boxEl)return;boxEl.innerHTML='';if(!series.length){boxEl.innerHTML='<div class="empty">暂无角色数据</div>';return;}series.forEach((s,i)=>{const row=s.latest,info=charInfo(s.slug),card=document.createElement('button');card.type='button';card.className='character-card';card.innerHTML=`<img src="${esc(info.icon_url)}" alt=""><div><div class="name">${esc(charName(s.slug))}</div><div class="meta">${esc(info.tier||'未分档')} · ${esc(info.element_cn||'')} · ${esc(info.style_cn||info.role_group_cn||'')}</div></div><div class="rate">${pct(row.app_rate)}</div>`;card.onclick=()=>{$('searchInput').value=charName(s.slug);state.search=charName(s.slug).toLowerCase();renderAnalysis();};boxEl.appendChild(card);});}
function renderChangelog(series){const boxEl=$('changelogList');if(!boxEl)return;boxEl.innerHTML='';const slugs=new Set(series.map(s=>s.slug));const related=(DATA.changelogRows||[]).filter(r=>String(r.character_slugs||'').split(';').some(slug=>slugs.has(slug)));const rows=(related.length?related:(DATA.changelogRows||[])).slice(0,8);if(!rows.length){boxEl.innerHTML='<div class="empty">暂无 changelog</div>';return;}rows.forEach(r=>{const item=document.createElement('div');item.className='changelog-item';const text=String(r.text||'');item.innerHTML=`<time>${esc(r.changelog_date||'')}</time><p>${esc(text.slice(0,420))}${text.length>420?'...':''}</p>`;boxEl.appendChild(item);});}
function initBox(){buttons('boxElementControl',[['all','全部'],...ELEMENTS.map(x=>[x,x])],box.element,v=>{box.element=v;renderBox();});buttons('boxStyleControl',[['all','全部'],...STYLES.map(x=>[x,x])],box.style,v=>{box.style=v;renderBox();});$('boxOwnedSelect').onchange=e=>{box.status=e.target.value;renderBox();};$('boxSearchInput').oninput=e=>{box.search=e.target.value.trim().toLowerCase();renderBox();};$('boxExportBtn').onclick=exportBox;$('boxImportBtn').onclick=()=>$('boxImportInput').click();$('boxImportInput').onchange=importBox;$('boxMarkVisibleBtn').onclick=()=>{filteredRoster().forEach(r=>box.owned.add(r.character_slug));saveBox();renderBox();};$('boxBuildVisibleBtn').onclick=()=>setVisibleBuild(true);$('boxClearBuildVisibleBtn').onclick=()=>setVisibleBuild(false);initBuild();}
function initBuild(){const levels=BUILD_LEVELS.map(v=>`<option value="${v}">${v?`${v}级`:'未录入'}</option>`).join('');$('buildLevel').innerHTML=levels;$('buildEngine').innerHTML=levels;$('buildSkill').innerHTML=BUILD_SKILLS.map(([v,l])=>`<option value="${v}">${l}</option>`).join('');$('buildDisc').innerHTML=BUILD_DISCS.map(([v,l])=>`<option value="${v}">${l}</option>`).join('');$('buildLevel').onchange=e=>buildSet('level',Number(e.target.value));$('buildEngine').onchange=e=>buildSet('engine',Number(e.target.value));$('buildSkill').onchange=e=>buildSet('skills',e.target.value);$('buildDisc').onchange=e=>buildSet('discs',e.target.value);$('buildMaxBtn').onclick=()=>{if(box.buildSlug){box.builds[box.buildSlug]=fullBuild();box.owned.add(box.buildSlug);saveBox();renderBox();}};$('buildClearBtn').onclick=()=>{delete box.builds[box.buildSlug];saveBox();renderBox();};}
function loadBox(){try{const raw=JSON.parse(localStorage.getItem(BOX_KEY)||'{}');box.owned=new Set(raw.owned||[]);box.builds=raw.builds||{};box.buildSlug=raw.buildSlug||'';}catch{box.owned=new Set();box.builds={};box.buildSlug='';}}
function saveBox(){localStorage.setItem(BOX_KEY,JSON.stringify({version:1,updatedAt:new Date().toISOString(),owned:[...box.owned].sort(),buildSlug:box.buildSlug,builds:box.builds}));}
function normBuild(b={}){const skills=BUILD_SKILLS.some(x=>x[0]===b.skills)?b.skills:'unset',discs=BUILD_DISCS.some(x=>x[0]===b.discs)?b.discs:'unset';return{level:BUILD_LEVELS.includes(Number(b.level))?Number(b.level):0,engine:BUILD_LEVELS.includes(Number(b.engine))?Number(b.engine):0,skills,discs};}
function optScore(opts,v){return opts.find(x=>x[0]===v)?.[2]||0}
function buildState(slug){const b=normBuild(box.builds[slug]||{}),score=(b.level/60)*.25+(b.engine/60)*.2+optScore(BUILD_SKILLS,b.skills)*.25+optScore(BUILD_DISCS,b.discs)*.3,recorded=!!(b.level||b.engine||b.skills!=='unset'||b.discs!=='unset'),ready=recorded&&score>=.86&&b.level>=55&&b.engine>=50&&optScore(BUILD_SKILLS,b.skills)>=.84&&optScore(BUILD_DISCS,b.discs)>=.84;return{...b,score,recorded,ready,percent:Math.round(score*100),label:ready?'已成型':recorded&&score>=.72?'可用':recorded?'待练':'练度未录入'};}
function fullBuild(){return{level:60,engine:60,skills:'max',discs:'great'}}
function setVisibleBuild(value){filteredRoster().forEach(r=>{if(value){box.owned.add(r.character_slug);box.builds[r.character_slug]=fullBuild();}else delete box.builds[r.character_slug];});saveBox();renderBox();}
function filteredRoster(){const q=box.search;return DATA.rosterRows.filter(r=>(box.element==='all'||r.element_cn===box.element)&&(box.style==='all'||r.style_cn===box.style)&&(box.status==='all'||(box.status==='owned')===box.owned.has(r.character_slug))&&(!q||[r.character_name_cn,r.character_name_en,r.character_slug,r.element_cn,r.style_cn].some(x=>String(x||'').toLowerCase().includes(q))));}
function renderBox(){const rows=filteredRoster(),owned=DATA.rosterRows.filter(r=>box.owned.has(r.character_slug)).length,built=DATA.rosterRows.filter(r=>box.owned.has(r.character_slug)&&buildState(r.character_slug).ready).length;renderBuild();$('boxSubtitle').textContent=`展示 ${rows.length}/${DATA.rosterRows.length} 个代理人，已拥有 ${owned}，已成型 ${built}`;$('boxBadges').innerHTML=[box.element==='all'?'全部属性':box.element,box.style==='all'?'全部特性':box.style,`成型 ${built}/${owned||0}`].map(x=>`<span>${esc(x)}</span>`).join('');const grid=$('boxGrid');grid.innerHTML='';rows.forEach(r=>{const owned=box.owned.has(r.character_slug),bs=buildState(r.character_slug);const card=document.createElement('article');card.className=`box-card ${owned?'owned':'missing'} ${box.buildSlug===r.character_slug?'selected':''}`;card.innerHTML=`<button class="build-btn">练度</button><img src="${esc(r.icon_url)}" alt=""><div class="name">${esc(r.character_name_cn||r.character_name_en)}</div><div class="meta">${esc(r.element_cn)} · ${esc(r.style_cn)}</div><div class="meta">${owned?`${bs.label} ${bs.recorded?bs.percent+'%':''}`:'未拥有'}</div>`;card.onclick=()=>{owned?box.owned.delete(r.character_slug):box.owned.add(r.character_slug);box.buildSlug=r.character_slug;saveBox();renderBox();};card.querySelector('.build-btn').onclick=e=>{e.stopPropagation();box.owned.add(r.character_slug);box.buildSlug=r.character_slug;saveBox();renderBox();};grid.appendChild(card);});}
function renderBuild(){const p=$('buildEditor');if(!box.buildSlug||!box.owned.has(box.buildSlug)){p.classList.add('hidden');return;}const r=charInfo(box.buildSlug),bs=buildState(box.buildSlug),b=normBuild(box.builds[box.buildSlug]||{});p.classList.remove('hidden');$('buildIcon').src=r.icon_url;$('buildTitle').textContent=`${charName(box.buildSlug)} · 练度`;$('buildSubtitle').textContent=`${r.element_cn} · ${r.style_cn}`;$('buildLevel').value=b.level;$('buildEngine').value=b.engine;$('buildSkill').value=b.skills;$('buildDisc').value=b.discs;$('buildScore').textContent=`${bs.label} · ${bs.percent}%`;}
function buildSet(k,v){if(!box.buildSlug)return;box.builds[box.buildSlug]={...normBuild(box.builds[box.buildSlug]||{}),[k]:v};box.owned.add(box.buildSlug);saveBox();renderBox();}
function exportBox(){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),owned:[...box.owned].sort(),builds:box.builds},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='zzz_box_state.json';a.click();URL.revokeObjectURL(a.href);}
function importBox(e){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const d=JSON.parse(String(reader.result||'{}'));box.owned=new Set(d.owned||[]);box.builds=d.builds||{};box.buildSlug='';saveBox();renderBox();}catch(err){alert(`导入失败：${err.message}`);}finally{e.target.value='';}};reader.readAsText(file);}
function initRec(){buttons('recModeControl',MODES,rec.mode,v=>{rec.mode=v;ensureScope();saveRec();syncRec();renderRec();});ELEMENTS.forEach(el=>{const b=document.createElement('button');b.textContent=el;b.onclick=()=>{const s=elementSet();s.has(el)?s.delete(el):s.add(el);rec.elements[key()]=[...s];saveRec();syncRec();renderRec();};$('recElementControl').appendChild(b);});$('recScopeSelect').onchange=e=>{rec.scope=e.target.value;saveRec();renderRec();};$('recGapSelect').onchange=e=>{rec.gap=e.target.value;saveRec();renderRec();};$('recRiskSelect').onchange=e=>{rec.riskMode=e.target.value;saveRec();renderRec();};$('recLimitSelect').onchange=e=>{rec.limit=e.target.value;saveRec();renderRec();};$('recSearchInput').oninput=e=>{rec.search=e.target.value.trim().toLowerCase();saveRec();renderRec();};ensureScope();}
function loadRec(){try{rec={...rec,...JSON.parse(localStorage.getItem(REC_KEY)||'{}')};}catch{}}
function saveRec(){localStorage.setItem(REC_KEY,JSON.stringify({...rec,updatedAt:new Date().toISOString()}));}
function key(){return `${rec.mode}|${rec.scope}`}
function elementSet(){return new Set(rec.elements?.[key()]||[])}
function scopes(){const map=new Map();DATA.teamTemplates.filter(t=>t.mode===rec.mode).forEach(t=>map.set(t.scope_key,{key:t.scope_key,label:t.scope_label}));return [...map.values()].sort((a,b)=>a.key.localeCompare(b.key));}
function ensureScope(){const ss=scopes();if(ss.length&&!ss.some(s=>s.key===rec.scope))rec.scope=ss[0].key;}
function syncRec(){const ss=scopes();$('recScopeSelect').innerHTML=ss.map(s=>`<option value="${esc(s.key)}">${esc(s.label)}</option>`).join('');$('recScopeSelect').value=rec.scope;$('recGapSelect').value=rec.gap;$('recRiskSelect').value=rec.riskMode;$('recLimitSelect').value=rec.limit||'8';$('recSearchInput').value=rec.search;const s=elementSet();[...$('recElementControl').children].forEach(b=>b.classList.toggle('active',s.has(b.textContent)));}
function tierMeta(slug){return DATA.tierRows.filter(r=>r.character_slug===slug&&r.tier_mode===rec.mode).sort((a,b)=>(TIER_RANK[a.tier]??9)-(TIER_RANK[b.tier]??9))[0]||{}}
function memberRisk(m){const risks=[],tier=tierMeta(m.slug),rank=TIER_RANK[tier.tier]??9,bs=m.build;if(m.owned){if(!bs.recorded)risks.push({text:'练度未录入',penalty:m.core?42:22});else if(bs.score<.68)risks.push({text:`练度待补 ${bs.percent}%`,penalty:m.core?70:36,severe:m.core});}if(rank>=5)risks.push({text:`${tier.tier}不建议投入${bs.ready?'（已练，降权）':''}`,penalty:bs.ready?35:90,severe:true});else if(rank>=3)risks.push({text:`${tier.tier}非主流低档${bs.ready?'（已练，降权）':''}`,penalty:bs.ready?25:62,severe:true});else if(rank>=1&&!bs.ready)risks.push({text:`${tier.tier}投入谨慎`,penalty:m.core?32:18});return risks;}
function scoreTeam(t,used=new Set()){const selected=elementSet();const members=t.chars.map(slug=>{const info=charInfo(slug),bs=buildState(slug),core=['crit_dps','anomaly_dps'].includes(info.role_group);return{slug,info,build:bs,owned:box.owned.has(slug),selected:selected.has(info.element_cn),core,conflict:used.has(slug)};});members.forEach(m=>m.risks=memberRisk(m));const owned=members.filter(m=>m.owned).length,ready=members.filter(m=>m.owned&&m.build.ready).length,miss=3-owned,elementHits=members.filter(m=>m.selected).length,coreHits=members.filter(m=>m.core&&m.selected).length,conflictCount=members.filter(m=>m.conflict&&m.owned).length,risks=members.flatMap(m=>m.risks.map(r=>({...r,name:charName(m.slug)})));if(selected.size&&members.some(m=>m.core)&&coreHits===0)risks.push({text:'主C均未命中推荐属性',penalty:145,severe:true});const penalty=rec.riskMode==='off'?0:risks.reduce((s,r)=>s+(r.penalty||0),0);let score=owned*46+members.filter(m=>m.owned).reduce((s,m)=>s+m.build.score*88,0)-miss*72-conflictCount*160+elementHits*12+coreHits*56+Math.min(num(t.app_rate)||0,35)*2.1-penalty;if(t.rank!=null)score+=Math.max(0,130-t.rank)*.4;if(selected.size&&elementHits===0)score-=35;return{template:t,members,ownedCount:owned,readyCount:ready,missingCount:miss,elementHits,coreHits,conflictCount,risks,score,search:[t.phase_name,t.scope_label,t.bangboo,t.bangboo_name,...t.chars,...t.names_cn,...risks.map(r=>r.text)].join(' ').toLowerCase()};}
function rankedFor(mode=rec.mode,scope=rec.scope,used=new Set(),ignoreSearch=false){return DATA.teamTemplates.filter(t=>t.mode===mode&&t.scope_key===scope).map(t=>scoreTeam(t,used)).filter(i=>i.missingCount<=Number(rec.gap)&&(rec.riskMode!=='filter'||!i.risks.length)&&(ignoreSearch||!rec.search||i.search.includes(rec.search))).sort((a,b)=>b.score-a.score||a.conflictCount-b.conflictCount||a.missingCount-b.missingCount||(a.template.rank||9999)-(b.template.rank||9999));}
function ranked(){return rankedFor();}
function phaseInfo(){const templates=DATA.teamTemplates.filter(t=>t.mode===rec.mode&&t.scope_key===rec.scope),latest=templates.slice().sort((a,b)=>String(b.collect_date).localeCompare(String(a.collect_date)))[0];const rows=DATA.phaseInfoRows||[];return rows.find(r=>r.mode===rec.mode&&r.phase_ver===latest?.phase_ver&&r.collect_date===latest?.collect_date)||rows.filter(r=>r.mode===rec.mode).sort((a,b)=>String(b.collect_date).localeCompare(String(a.collect_date)))[0]||{};}
function renderPhaseInfo(){const p=phaseInfo();$('phaseTitle').textContent=`${p.mode_cn||MODES.find(x=>x[0]===rec.mode)?.[1]||rec.mode} · ${p.phase_name_cn||p.phase_name||p.phase_ver||'当期数据'}`;$('phaseDates').textContent=`${p.start_date||'未知'} 至 ${p.end_date||'未知'} · 采样 ${p.collect_date||'未知'}`;$('phaseText').textContent=p.mechanic_text||'推荐限定当前同模式、同关卡数据源。';}
function renderRec(){ensureScope();syncRec();renderPhaseInfo();const rows=ranked().slice(0,Number(rec.limit)||8),sel=[...elementSet()],templates=DATA.teamTemplates.filter(t=>t.mode===rec.mode&&t.scope_key===rec.scope);$('recTitle').textContent=`${MODES.find(x=>x[0]===rec.mode)?.[1]} · ${scopes().find(s=>s.key===rec.scope)?.label||rec.scope}`;$('recSubtitle').textContent=`当前同模式同关卡模板 ${templates.length} 队`;const riskLabel=rec.riskMode==='filter'?'过滤风险':rec.riskMode==='off'?'忽略风险':'仅提醒';$('recBadges').innerHTML=[sel.length?sel.join(' / '):'未选属性',`缺口 ≤ ${rec.gap}`,riskLabel,rec.riskMode==='off'?'T档不提醒':'T1及以下提醒',`Box ${box.owned.size}`].map(x=>`<span>${esc(x)}</span>`).join('');const list=$('recList');list.innerHTML='';if(!rows.length){list.innerHTML='<div class="empty">当前筛选没有可展示队伍</div>';renderRecSlate();return;}rows.forEach((item,i)=>list.appendChild(recCard(item,i+1)));renderRecSlate();}
function recCard(item,i){const t=item.template,card=document.createElement('article');card.className=`rec-card ${item.risks.length&&rec.riskMode!=='off'?'risky':''}`;card.innerHTML=`<div class="rec-head"><div><h3>${i}. ${esc(t.names_cn.join(' / '))}</h3><div class="rec-meta">${esc(t.scope_label)} · Rank ${t.rank??'-'} · ${pct(t.app_rate)} · 邦布 ${esc(bangbooName(t.bangboo,t.bangboo_name))}</div></div><div class="score">${Math.round(item.score)}<br><span>${item.ownedCount}/3</span></div></div><div class="rec-team">${item.members.map(m=>memberHtml(m)).join('')}</div><div class="tags"><span class="${item.missingCount?'warn':''}">${item.missingCount?`缺 ${item.missingCount}`:'可成队'}</span>${item.ownedCount?`<span class="${item.readyCount<item.ownedCount?'warn':''}">练度 ${item.readyCount}/${item.ownedCount}</span>`:''}<span>属性命中 ${item.elementHits}</span>${item.conflictCount?`<span class="warn">多队冲突 ${item.conflictCount}</span>`:''}${item.risks.length&&rec.riskMode!=='off'?`<span class="${item.risks.some(r=>r.severe)?'danger':'warn'}">风险 ${item.risks.length}</span>`:''}</div>${riskHtml(item)}`;return card;}
function memberHtml(m){const risky=(m.risks.length&&rec.riskMode!=='off')||m.conflict;return `<div class="rec-member ${m.owned?'owned':'missing'} ${risky?'risky':''}"><img src="${esc(m.info.icon_url)}" alt=""><div class="name">${esc(charName(m.slug))}</div><div class="meta">${esc(m.info.element_cn)} · ${esc(m.info.style_cn)}${m.owned?` · ${esc(m.build.label)}`:''}${m.conflict?' · 冲突':''}</div></div>`;}
function riskHtml(item){if(!item.risks.length||rec.riskMode==='off')return '';return `<div class="risk-note">${esc(item.risks.slice(0,4).map(r=>r.name?`${r.name}：${r.text}`:r.text).join('；'))}${item.risks.length>4?'；...':''}</div>`;}
function renderRecSlate(){const list=$('recSlateList'),scopeList=scopes().filter(s=>s.key!=='all');list.innerHTML='';const used=new Set(),chosen=[];scopeList.forEach(scope=>{const item=rankedFor(rec.mode,scope.key,used,true).find(x=>x.conflictCount===0)||rankedFor(rec.mode,scope.key,used,true)[0];if(item){item.members.filter(m=>m.owned).forEach(m=>used.add(m.slug));}chosen.push({scope,item});});$('recSlateSubtitle').textContent=`${chosen.filter(x=>x.item).length}/${scopeList.length} 队 · 尽量不复用已拥有角色`;if(!chosen.length){list.innerHTML='<div class="empty">暂无当前模式关卡模板</div>';return;}chosen.forEach(({scope,item})=>{const card=document.createElement('div');card.className=`rec-slate-card ${item?.risks?.length&&rec.riskMode!=='off'?'risky':''}`;if(!item){card.innerHTML=`<h3>${esc(scope.label)}</h3><div class="rec-meta">没有符合缺口限制的队伍</div>`;}else{card.innerHTML=`<h3>${esc(scope.label)} · ${Math.round(item.score)} · ${item.ownedCount}/3</h3><div class="rec-slate-team">${item.members.map(m=>`<img class="${m.owned?'':'missing'} ${m.risks.length&&rec.riskMode!=='off'?'risky':''}" src="${esc(m.info.icon_url)}" title="${esc(charName(m.slug))}" alt="">`).join('')}</div>${riskHtml(item)}`;}list.appendChild(card);});}
