[package]
name = "miho-cli"
version.workspace = true
edition.workspace = true

[features]
automation-no-window = []

[[bin]]
name = "miho"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
chrono.workspace = true
miho-app = { path = "../miho-app" }
miho-core = { path = "../miho-core" }
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
