[package]
name = "miho-desktop"
version.workspace = true
edition.workspace = true

[lib]
name = "miho_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = ["isolation"] }

[dependencies]
miho-app = { path = "../../miho-app" }
miho-core = { path = "../../miho-core" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tauri = { version = "2", features = ["isolation"] }
tauri-plugin-dialog = "=2.7.1"
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
anyhow.workspace = true
